---
postgres:
  host: localhost
  port: 5432
  user: pgsql_health_check_monitor
  password: very_secret_password
  dbname: postgres
server:
  port: 8080
  host: localhost
  # allowed
  # debug
  # release
  mode: debug