---
postgres:
  host: localhost
  port: 5432
  user: pgsql_health_check_monitor
  password: very_secret_password
  dbname: postgres
server:
  port: 8080
  host: localhost
  mode: release # debug, release set release for production
log:
  collector: stdout
  level: info
#  syslog:
#    host:         # syslog server host
#    local:        # local0 # available: local0, local1, local2, local3, local4, local5, local6, local7
#    protocol: tcp # tcp, udp
#    level: debug  # debug info warn error fatal panic